name: "Build and publish package"

on:
  push:
    tags:
      - '*'

jobs:
  tests-before-build:
    uses: ./.github/workflows/test.yaml

  build:
    name: "Build package"
    runs-on: ubuntu-latest
    needs: tests-before-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build packages
        run: |
          mkdir dist
          echo "hello world" > dist/package.txt

      - name: Save packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/*

  upload:
    name: "Upload package"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve packages
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist-files

      - name: Verify packages
        run: ls -al
        working-directory: dist-files
