name: Run tests

on:
  push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run:
        # test is failing
        echo "All is not so well" && exit 1
